import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
// GitHub Pages publishes this repository's root. Keep original URLs intact.
const out = path.dirname(root);
const config = JSON.parse(await fs.readFile(path.join(root,'site.config.json'),'utf8'));
const posts = JSON.parse(await fs.readFile(path.join(root,'content/posts.json'),'utf8')).sort((a,b)=>b.date.localeCompare(a.date));
const categories = [...new Set(posts.map(p=>p.category))].sort((a,b)=>['AI学习','课程笔记','生活随笔'].indexOf(a)-['AI学习','课程笔记','生活随笔'].indexOf(b));
const labels = {'AI学习':'AI 學習','课程笔记':'課程筆記','生活随笔':'生活隨筆'};
const e = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href = value => e(encodeURI(value));
const arrow = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M3 10h13m-5-5 5 5-5 5" stroke="currentColor" stroke-width="1.25"/></svg>';
const backArrow = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M17 10H4m5-5-5 5 5 5" stroke="currentColor" stroke-width="1.25"/></svg>';
const categoryURL = category => '/categories/'+category+'/';
const dateLabel = date => date.replaceAll('-','.');
const categoryLabel = c => labels[c]||c;
const desc = p => p.excerpt;
const metadata = p => `<div class="post-meta"><time datetime="${e(p.date)}">${dateLabel(p.date)}</time><span class="meta-dot" aria-hidden="true"></span><span>約 ${p.minutes} 分鐘閱讀</span></div>`;
function card(p){return `<article class="post-card"><a href="${href(p.url)}"><span class="post-category"><span class="category-square" aria-hidden="true"></span>${e(categoryLabel(p.category))}</span><h3>${e(p.title)}</h3><p>${e(desc(p))}</p><div class="post-card-bottom">${metadata(p)}<span class="post-card-arrow">${arrow}</span></div></a></article>`;}
function filters(current='全部'){return `<nav class="filter-bar" aria-label="文章分類"><a class="filter ${current==='全部'?'selected':''}" href="/" ${current==='全部'?'aria-current="page"':''}>全部<span class="filter-count">${posts.length}</span></a>${categories.map(c=>`<a class="filter ${current===c?'selected':''}" href="${href(categoryURL(c))}" ${current===c?'aria-current="page"':''}>${e(categoryLabel(c))}<span class="filter-count">${posts.filter(p=>p.category===c).length}</span></a>`).join('')}</nav>`;}
function layout(main,{title='',description=config.description,nav='home',url='/',article=null}={}){
  const pageTitle=title?title+' · '+config.title:config.title+' · 記錄所學，也記錄生活';
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f8f9f5"><meta name="description" content="${e(description)}"><title>${e(pageTitle)}</title><link rel="canonical" href="${e(config.origin+encodeURI(url))}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${e(pageTitle)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(config.origin+encodeURI(url))}"><meta name="twitter:card" content="summary">${article?`<meta property="article:published_time" content="${e(article.date)}"><meta property="article:author" content="${e(config.author)}">`:''}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='10' fill='%234d6254'/%3E%3Cpath d='M12 10v20m16-20v20M12 20h16' stroke='%23f8f9f5' stroke-width='3' fill='none'/%3E%3C/svg%3E"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body id="top"><a class="skip-link" href="#main">跳至主要內容</a><header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="${e(config.title)} 首頁"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M7 6v16M21 6v16M7 14h14"/><path class="mark-detail" d="M11 4h6M11 24h6"/></svg></span><span>${e(config.title)}</span></a><nav class="main-nav" aria-label="主要導覽">${[['home','/','文章'],['archive','/archives/','歸檔'],['about','/about/','關於']].map(([key,to,label])=>`<a href="${to}" ${nav===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><span class="header-note"><span class="status-dot"></span>持續記錄中</span></div></header><main id="main" tabindex="-1">${main}</main><footer class="site-footer"><div class="footer-inner"><div><a class="footer-brand" href="/">${e(config.title)}</a><p>用文字，留下一點痕跡。</p></div><div class="footer-right"><div class="footer-links"><a href="${e(config.github)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="/about/">關於這裡 ↗</a></div><span>© ${new Date().getUTCFullYear()} ${e(config.author)} · ${e(config.title)}</span></div></div></footer>${article?'<a class="back-to-top" href="#top" aria-label="返回頂部">↑</a>':''}</body></html>`;
}
const featured=posts.find(p=>p.featured)||posts[0];
const featuredHTML=`<section class="featured reveal delay-2" aria-label="精選文章"><a class="featured-link" href="${href(featured.url)}"><div><span class="featured-label"><svg viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M6 1l1.4 3.1L11 5.2 8.3 7.4l.1 3.6L6 9.2 2.8 11l.9-3.6L1 5.2l3.6-1.1L6 1Z" stroke="currentColor" stroke-width=".8"/></svg>精選筆記<span class="feature-label-divider">/</span>${e(categoryLabel(featured.category))}</span><h2>${e(featured.featureTitle || featured.title).split("\n").join("<br>")}</h2><p>${e(desc(featured))}</p>${metadata(featured)}</div><div class="feature-art" aria-hidden="true"><span class="small-star">✳</span><span class="small-dot"></span><div class="notebook"><div class="notebook-title">Learn.<br>Think.<br>Write.</div><span class="notebook-sub">A PERSONAL NOTEBOOK</span><span class="notebook-line"></span><span class="notebook-line"></span></div><span class="orbit-label">one note at a time.</span></div><span class="feature-arrow">${arrow}</span></a></section>`;
const home=`<div class="container"><section class="hero reveal"><div><span class="eyebrow">A PERSONAL NOTEBOOK</span><h1>記錄所學，<br><span class="second-line">也記錄走過的路。</span></h1><p class="hero-copy">在這裡，整理學習筆記，分享實踐心得，<br>也收藏日常裡值得記住的片刻。</p></div><aside class="hero-aside reveal delay-1"><span class="aside-label">LEARNING, IN PROGRESS</span><h2 class="aside-title">學習 · 思考 · 記錄</h2><p>把一點一滴的探索，<br>慢慢整理成自己的知識。</p><span class="aside-bottom">SINCE 2026 &nbsp; / &nbsp; ${String(posts.length).padStart(2,'0')} NOTES</span></aside></section>${featuredHTML}<section class="recent-posts reveal delay-3" aria-labelledby="recent-title"><div class="section-header"><div class="section-heading"><h2 id="recent-title">最近記錄</h2><span>RECENT NOTES</span></div><span class="section-note">共 ${posts.length} 篇文章</span></div>${filters()}<div class="posts-grid">${posts.filter(p=>p!==featured).map(card).join('')}</div></section><div class="closing-note"><span class="asterisk" aria-hidden="true">✳</span><p>不急著抵達，先把每一步記下來。</p></div></div>`;
const pages = new Map([['/',layout(home)]]);
for(const category of categories){
  const categoryPosts=posts.filter(p=>p.category===category);
  const intro={'AI学习':'從基礎概念到模型原理，一點一點理解 AI。','课程笔记':'把課堂所學整理成筆記，讓知識有跡可循。','生活随笔':'在學習與程式碼之外，記住生活裡的一點光。'}[category]||'關於這個主題的學習與記錄。';
  pages.set(categoryURL(category),layout(`<div class="container archive-container"><header class="page-intro reveal"><span class="eyebrow">NOTE COLLECTION</span><h1>${e(categoryLabel(category))}</h1><p>${intro}</p></header>${filters(category)}<div class="posts-grid">${categoryPosts.map(card).join('')}</div></div>`,{title:categoryLabel(category),description:intro,url:categoryURL(category)}));
}
const categoryIndex=`<div class="container archive-container"><header class="page-intro"><span class="eyebrow">COLLECTIONS</span><h1>筆記分類</h1><p>從感興趣的主題開始閱讀。</p></header><div class="category-grid">${categories.map((c,i)=>`<a class="category-tile" href="${href(categoryURL(c))}"><span class="category-number">0${i+1}</span><h2>${e(categoryLabel(c))}</h2><p>${posts.filter(p=>p.category===c).length} 篇文章</p><span>${arrow}</span></a>`).join('')}</div></div>`;
pages.set('/categories/',layout(categoryIndex,{title:'分類',url:'/categories/'}));
const months=[...new Set(posts.map(p=>p.date.slice(0,7)))];
const archive=`<div class="container archive-container"><header class="page-intro reveal"><span class="eyebrow">THE NOTE ARCHIVE</span><h1>時間裡的筆記</h1><p>${posts.length} 篇文章，${categories.length} 個主題。每一次記錄，都是一次小小的累積。</p></header>${months.map(month=>`<section class="archive-group"><h2 class="archive-month">${month.replace('-',' / ')}<span>${posts.filter(p=>p.date.startsWith(month)).length} 篇記錄</span></h2><div>${posts.filter(p=>p.date.startsWith(month)).map(p=>`<a class="archive-entry" href="${href(p.url)}"><time datetime="${e(p.date)}">${p.date.slice(5).replace('-','.')}</time><h3>${e(p.title)}</h3><span class="post-category">${e(categoryLabel(p.category))}</span>${arrow}</a>`).join('')}</div></section>`).join('')}</div>`;
pages.set('/archives/',layout(archive,{title:'歸檔',nav:'archive',url:'/archives/'}));
for(const year of [...new Set(posts.map(p=>p.date.slice(0,4)))])pages.set('/archives/'+year+'/',layout(archive,{title:year+' 年歸檔',nav:'archive',url:'/archives/'+year+'/'}));
for(const month of months)pages.set('/archives/'+month.replace('-','/')+'/',layout(archive,{title:month+' 歸檔',nav:'archive',url:'/archives/'+month.replace('-','/')+'/'}));
const about=`<div class="container"><header class="page-intro reveal"><span class="eyebrow">BEHIND THE NOTES</span><h1>你好，我是木之風。</h1><p>正在把學習，變成一件長久的事。</p></header><div class="about-layout"><div class="about-copy"><p>這裡是 Hickercf'blog，一本持續更新的個人筆記本。</p><p>我在這裡記錄 AI 學習、課程筆記、工具探索與生活碎片。它不限定在某個固定方向，而是跟著每一次好奇、練習與實踐，慢慢留下自己的學習軌跡。</p><h2>我在這裡寫些什麼</h2><ul><li><a href="${href(categoryURL('AI学习'))}">AI 學習</a>：從 Python 基礎到大型語言模型，記錄探索與理解。</li><li><a href="${href(categoryURL('课程笔记'))}">課程筆記</a>：整理作業系統、資料庫、編譯原理與組合語言。</li><li><a href="${href(categoryURL('生活随笔'))}">生活隨筆</a>：在程式碼與書本之外，收藏日常裡的想法。</li></ul><h2>保持好奇，持續記錄</h2><p>比起把內容包裝得很宏大，我更希望這裡能留下真實的學習過程。看懂了什麼、還在思考什麼，都值得寫下來。</p><p>如果這些筆記恰好對你有幫助，很高興我們在這裡相遇。</p><a class="text-link" href="${e(config.github)}" target="_blank" rel="noopener noreferrer">在 GitHub 找到我 ↗</a></div><aside class="about-card"><div class="big-h" aria-hidden="true">H.</div><h2>${e(config.title)}</h2><p>在程式碼、書本<br>和凌晨三點之間遊蕩。</p><span class="tiny-label">A NOTEBOOK, ALWAYS OPEN.</span></aside></div></div>`;
pages.set('/about/',layout(about,{title:'關於',nav:'about',url:'/about/'}));
for(const p of posts){
  const content=await fs.readFile(path.join(root,'content',p.content),'utf8');
  const toc=p.headings.map(h=>`<a href="#${e(encodeURIComponent(h.id))}">${e(h.text)}</a>`).join('');
  const next=posts.find(other=>other!==p&&other.category===p.category)||posts.find(other=>other!==p);
  const reader=`<article class="reader-container"><a class="back-link" href="/">${backArrow}返回所有文章</a><header class="reader-heading"><a class="post-category" href="${href(categoryURL(p.category))}"><span class="category-square" aria-hidden="true"></span>${e(categoryLabel(p.category))}</a><h1>${e(p.title)}</h1>${metadata(p)}<p class="reader-excerpt">${e(desc(p))}</p></header>${toc?`<details class="mobile-toc"><summary>文章目錄 <span>${p.headings.length} 個章節</span></summary><nav aria-label="文章章節">${toc}</nav></details>`:''}${p.missingImages?`<p class="attachment-note">原文中的 ${p.missingImages} 張圖片未附在網站檔案中，文字內容已保留。</p>`:''}<div class="reader-layout"><div><div class="reader-body" lang="zh-CN">${content}</div><div class="reader-end"><p>寫下來，是為了更好地理解。<br>— ${e(config.author)}</p></div>${next?`<a class="reader-next" href="${href(next.url)}"><span>繼續閱讀 · ${e(categoryLabel(next.category))}</span><h2>${e(next.title)} <span aria-hidden="true">→</span></h2></a>`:''}</div>${toc?`<aside class="reader-toc"><h2>ON THIS PAGE · 文章目錄</h2><nav aria-label="文章章節">${toc}</nav></aside>`:''}</div></article>`;
  pages.set(p.url,layout(reader,{title:p.title,description:desc(p),url:p.url,article:p}));
}
await fs.mkdir(out,{recursive:true});
await fs.copyFile(path.join(root,'styles.css'),path.join(out,'styles.css'));
await fs.copyFile(path.join(root,'app.js'),path.join(out,'app.js'));
for(const [url,html] of pages){const destination=path.join(out,url,'index.html');await fs.mkdir(path.dirname(destination),{recursive:true});await fs.writeFile(destination,html);}
await fs.writeFile(path.join(out,'404.html'),layout('<div class="empty-state"><span class="eyebrow">PAGE NOT FOUND</span><h1>這一頁，還沒寫下來。</h1><p>連結可能已變更，回到文章列表找找看吧。</p><a class="text-link" href="/">回到首頁 →</a></div>',{title:'找不到頁面',nav:''}));
try{await fs.cp(path.join(root,'content/assets'),path.join(out,'assets'),{recursive:true});}catch(error){if(error.code!=='ENOENT')throw error;}
await fs.writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...pages.keys()].map(url=>`<url><loc>${e(config.origin+encodeURI(url))}</loc></url>`).join('')}</urlset>`);
await fs.writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${config.origin}/sitemap.xml\n`);
console.log(JSON.stringify({pages:pages.size,articles:posts.length,categories:categories.length,missingImages:posts.reduce((total,p)=>total+(p.missingImages||0),0),output:out}));
