import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
// GitHub Pages publishes this repository's root. Keep original URLs intact.
const out = path.dirname(root);
const config = JSON.parse(await fs.readFile(path.join(root,'site.config.json'),'utf8'));
const posts = JSON.parse(await fs.readFile(path.join(root,'content/posts.json'),'utf8')).sort((a,b)=>b.date.localeCompare(a.date));
const categories = [...new Set(posts.map(p=>p.category))].sort((a,b)=>['渗透学习','AI学习','课程笔记','生活随笔'].indexOf(a)-['渗透学习','AI学习','课程笔记','生活随笔'].indexOf(b));
const labels = {'渗透学习':'渗透学习','AI学习':'AI 学习','课程笔记':'课程笔记','生活随笔':'生活随笔'};
const e = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href = value => e(encodeURI(value));
const arrow = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M3 10h13m-5-5 5 5-5 5" stroke="currentColor" stroke-width="1.25"/></svg>';
const backArrow = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M17 10H4m5-5-5 5 5 5" stroke="currentColor" stroke-width="1.25"/></svg>';
const categoryURL = category => '/categories/'+category+'/';
const dateLabel = date => date.replaceAll('-','.');
const categoryLabel = c => labels[c]||c;
const desc = p => p.excerpt;
const metadata = p => `<div class="post-meta"><time datetime="${e(p.date)}">${dateLabel(p.date)}</time><span class="meta-dot" aria-hidden="true"></span><span>约 ${p.minutes} 分钟阅读</span></div>`;
function card(p){return `<article class="post-card"><a href="${href(p.url)}"><span class="post-category"><span class="category-square" aria-hidden="true"></span>${e(categoryLabel(p.category))}</span><h3>${e(p.title)}</h3><p>${e(desc(p))}</p><div class="post-card-bottom">${metadata(p)}<span class="post-card-arrow">${arrow}</span></div></a></article>`;}
function filters(current='全部'){return `<nav class="filter-bar" aria-label="文章分类"><a class="filter ${current==='全部'?'selected':''}" href="/" ${current==='全部'?'aria-current="page"':''}>全部<span class="filter-count">${posts.length}</span></a>${categories.map(c=>`<a class="filter ${current===c?'selected':''}" href="${href(categoryURL(c))}" ${current===c?'aria-current="page"':''}>${e(categoryLabel(c))}<span class="filter-count">${posts.filter(p=>p.category===c).length}</span></a>`).join('')}</nav>`;}
function layout(main,{title='',description=config.description,nav='home',url='/',article=null}={}){
  const pageTitle=title?title+' · '+config.title:config.title+' · 记录所学，也记录生活';
  return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f8f9f5"><meta name="description" content="${e(description)}"><title>${e(pageTitle)}</title><link rel="canonical" href="${e(config.origin+encodeURI(url))}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${e(pageTitle)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(config.origin+encodeURI(url))}"><meta name="twitter:card" content="summary">${article?`<meta property="article:published_time" content="${e(article.date)}"><meta property="article:author" content="${e(config.author)}">`:''}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='10' fill='%234d6254'/%3E%3Cpath d='M12 10v20m16-20v20M12 20h16' stroke='%23f8f9f5' stroke-width='3' fill='none'/%3E%3C/svg%3E"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body id="top"><a class="skip-link" href="#main">跳至主要内容</a><header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="${e(config.title)} 首页"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M7 6v16M21 6v16M7 14h14"/><path class="mark-detail" d="M11 4h6M11 24h6"/></svg></span><span>${e(config.title)}</span></a><nav class="main-nav" aria-label="主导航">${[['home','/','文章'],['archive','/archives/','归档'],['about','/about/','关于']].map(([key,to,label])=>`<a href="${to}" ${nav===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><span class="header-note"><span class="status-dot"></span>持续记录中</span></div></header><main id="main" tabindex="-1">${main}</main><footer class="site-footer"><div class="footer-inner"><div><a class="footer-brand" href="/">${e(config.title)}</a><p>用文字，留下一点痕迹。</p></div><div class="footer-right"><div class="footer-links"><a href="${e(config.github)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="/about/">关于这里 ↗</a></div><span>© ${new Date().getUTCFullYear()} ${e(config.author)} · ${e(config.title)}</span></div></div></footer>${article?'<a class="back-to-top" href="#top" aria-label="返回顶部">↑</a>':''}</body></html>`;
}
const featured=posts.find(p=>p.featured)||posts[0];
const featuredHTML=`<section class="featured reveal delay-2" aria-label="精选文章"><a class="featured-link" href="${href(featured.url)}"><div><span class="featured-label"><svg viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M6 1l1.4 3.1L11 5.2 8.3 7.4l.1 3.6L6 9.2 2.8 11l.9-3.6L1 5.2l3.6-1.1L6 1Z" stroke="currentColor" stroke-width=".8"/></svg>精选笔记<span class="feature-label-divider">/</span>${e(categoryLabel(featured.category))}</span><h2>${e(featured.featureTitle || featured.title).split("\n").join("<br>")}</h2><p>${e(desc(featured))}</p>${metadata(featured)}</div><div class="feature-art" aria-hidden="true"><span class="small-star">✳</span><span class="small-dot"></span><div class="notebook"><div class="notebook-title">学习<br>思考<br>记录</div><span class="notebook-sub">个人学习笔记</span><span class="notebook-line"></span><span class="notebook-line"></span></div><span class="orbit-label">一点一滴，皆有所得</span></div><span class="feature-arrow">${arrow}</span></a></section>`;
const home=`<div class="container"><section class="hero reveal"><div><span class="eyebrow">个人学习笔记</span><h1>记录所学，<br><span class="second-line">也记录走过的路。</span></h1><p class="hero-copy">在这里，整理学习笔记，分享实践心得，<br>也收藏日常里值得记住的片刻。</p></div><aside class="hero-aside reveal delay-1"><span class="aside-label">持续学习，持续记录</span><h2 class="aside-title">学习 · 思考 · 记录</h2><p>把一点一滴的探索，<br>慢慢整理成自己的知识。</p><span class="aside-bottom">始于 2026 年 &nbsp; / &nbsp; ${String(posts.length).padStart(2,'0')} 篇笔记</span></aside></section>${featuredHTML}<section class="recent-posts reveal delay-3" aria-labelledby="recent-title"><div class="section-header"><div class="section-heading"><h2 id="recent-title">最近记录</h2><span>最近更新</span></div><span class="section-note">共 ${posts.length} 篇文章</span></div>${filters()}<div class="posts-grid">${posts.filter(p=>p!==featured).map(card).join('')}</div></section><div class="closing-note"><span class="asterisk" aria-hidden="true">✳</span><p>不急着抵达，先把每一步记下来。</p></div></div>`;
const pages = new Map([['/',layout(home)]]);
for(const category of categories){
  const categoryPosts=posts.filter(p=>p.category===category);
  const intro={'渗透学习':'从网络基础到工具使用，把漏洞原理和实验过程整理成自己的安全学习笔记。','AI学习':'从基础概念到模型原理，一点一点理解 AI。','课程笔记':'把课堂所学整理成笔记，让知识有迹可循。','生活随笔':'在学习与代码之外，记住生活里的一点光。'}[category]||'关于这个主题的学习与记录。';
  pages.set(categoryURL(category),layout(`<div class="container archive-container"><header class="page-intro reveal"><span class="eyebrow">专题笔记</span><h1>${e(categoryLabel(category))}</h1><p>${intro}</p></header>${filters(category)}<div class="posts-grid">${categoryPosts.map(card).join('')}</div></div>`,{title:categoryLabel(category),description:intro,url:categoryURL(category)}));
}
const categoryIndex=`<div class="container archive-container"><header class="page-intro"><span class="eyebrow">内容分类</span><h1>笔记分类</h1><p>从感兴趣的主题开始阅读。</p></header><div class="category-grid">${categories.map((c,i)=>`<a class="category-tile" href="${href(categoryURL(c))}"><span class="category-number">0${i+1}</span><h2>${e(categoryLabel(c))}</h2><p>${posts.filter(p=>p.category===c).length} 篇文章</p><span>${arrow}</span></a>`).join('')}</div></div>`;
pages.set('/categories/',layout(categoryIndex,{title:'分类',url:'/categories/'}));
const months=[...new Set(posts.map(p=>p.date.slice(0,7)))];
function archiveHTML(prefix=''){
  const scopedPosts=posts.filter(p=>p.date.startsWith(prefix));
  const scopedMonths=[...new Set(scopedPosts.map(p=>p.date.slice(0,7)))];
  const scopedCategories=new Set(scopedPosts.map(p=>p.category));
  return `<div class="container archive-container"><header class="page-intro reveal"><span class="eyebrow">时间归档</span><h1>${prefix?e(prefix.replace('-',' / '))+' 的笔记':'时间里的笔记'}</h1><p>${scopedPosts.length} 篇文章，${scopedCategories.size} 个主题。每一次记录，都是一次小小的累积。</p></header>${scopedMonths.map(month=>`<section class="archive-group"><h2 class="archive-month"><a href="/archives/${month.replace('-','/')}/">${month.replace('-',' / ')}</a><span>${scopedPosts.filter(p=>p.date.startsWith(month)).length} 篇记录</span></h2><div>${scopedPosts.filter(p=>p.date.startsWith(month)).map(p=>`<a class="archive-entry" href="${href(p.url)}"><time datetime="${e(p.date)}">${p.date.slice(5).replace('-','.')}</time><h3>${e(p.title)}</h3><span class="post-category">${e(categoryLabel(p.category))}</span>${arrow}</a>`).join('')}</div></section>`).join('')}</div>`;
}
pages.set('/archives/',layout(archiveHTML(),{title:'归档',nav:'archive',url:'/archives/'}));
for(const year of [...new Set(posts.map(p=>p.date.slice(0,4)))])pages.set('/archives/'+year+'/',layout(archiveHTML(year),{title:year+' 年归档',nav:'archive',url:'/archives/'+year+'/'}));
for(const month of months)pages.set('/archives/'+month.replace('-','/')+'/',layout(archiveHTML(month),{title:month+' 归档',nav:'archive',url:'/archives/'+month.replace('-','/')+'/'}));
const about=`<div class="container"><header class="page-intro reveal"><span class="eyebrow">关于这里</span><h1>你好，我是木之风。</h1><p>正在把学习，变成一件长久的事。</p></header><div class="about-layout"><div class="about-copy"><p>这里是 Hickercf'blog，一本持续更新的个人笔记本。</p><p>我在这里记录渗透学习、AI 探索、课程笔记与生活碎片。它不限定在某个固定方向，而是跟着每一次好奇、练习与实践，慢慢留下自己的学习轨迹。</p><h2>我在这里写些什么</h2><ul><li><a href="${href(categoryURL('渗透学习'))}">渗透学习</a>：从网络基础到 SQL 注入、工具使用与实验复现，整理原理和实践心得。</li><li><a href="${href(categoryURL('AI学习'))}">AI 学习</a>：从 Python 基础到大语言模型，记录探索与理解。</li><li><a href="${href(categoryURL('课程笔记'))}">课程笔记</a>：整理操作系统、数据库、编译原理与汇编语言。</li><li><a href="${href(categoryURL('生活随笔'))}">生活随笔</a>：在代码与书本之外，收藏日常里的想法。</li></ul><h2>保持好奇，持续记录</h2><p>比起把内容包装得很宏大，我更希望这里能留下真实的学习过程。看懂了什么、还在思考什么，都值得写下来。</p><p>如果这些笔记恰好对你有帮助，很高兴我们在这里相遇。</p><a class="text-link" href="${e(config.github)}" target="_blank" rel="noopener noreferrer">在 GitHub 找到我 ↗</a></div><aside class="about-card"><div class="big-h" aria-hidden="true">H.</div><h2>${e(config.title)}</h2><p>在代码、书本<br>和凌晨三点之间游荡。</p><span class="tiny-label">记录每一步学习</span></aside></div></div>`;
pages.set('/about/',layout(about,{title:'关于',nav:'about',url:'/about/'}));
for(const p of posts){
  const content=await fs.readFile(path.join(root,'content',p.content),'utf8');
  const toc=p.headings.map(h=>`<a href="#${e(encodeURIComponent(h.id))}">${e(h.text)}</a>`).join('');
  const next=posts.find(other=>other!==p&&other.category===p.category)||posts.find(other=>other!==p);
  const reader=`<article class="reader-container"><a class="back-link" href="/">${backArrow}返回所有文章</a><header class="reader-heading"><a class="post-category" href="${href(categoryURL(p.category))}"><span class="category-square" aria-hidden="true"></span>${e(categoryLabel(p.category))}</a><h1>${e(p.title)}</h1>${metadata(p)}<p class="reader-excerpt">${e(desc(p))}</p></header>${p.source?.type==='notion'?`<p class="source-note">整理自个人 Notion 笔记 · 原笔记更新于 <time datetime="${e(p.source.updatedAt.slice(0,10))}">${dateLabel(p.source.updatedAt.slice(0,10))}</time></p>`:''}${toc?`<details class="mobile-toc"><summary>文章目录 <span>${p.headings.length} 个章节</span></summary><nav aria-label="文章章节">${toc}</nav></details>`:''}${p.missingImages?`<p class="attachment-note">原文中的 ${p.missingImages} 张图片未附在网站文件中，文字内容已保留。</p>`:''}<div class="reader-layout"><div><div class="reader-body" lang="zh-CN">${content}</div><div class="reader-end"><p>写下来，是为了更好地理解。<br>— ${e(config.author)}</p></div>${next?`<a class="reader-next" href="${href(next.url)}"><span>继续阅读 · ${e(categoryLabel(next.category))}</span><h2>${e(next.title)} <span aria-hidden="true">→</span></h2></a>`:''}</div>${toc?`<aside class="reader-toc"><h2>文章目录</h2><nav aria-label="文章章节">${toc}</nav></aside>`:''}</div></article>`;
  pages.set(p.url,layout(reader,{title:p.title,description:desc(p),url:p.url,article:p}));
}
await fs.mkdir(out,{recursive:true});
await fs.copyFile(path.join(root,'styles.css'),path.join(out,'styles.css'));
await fs.copyFile(path.join(root,'app.js'),path.join(out,'app.js'));
for(const [url,html] of pages){const destination=path.join(out,url,'index.html');await fs.mkdir(path.dirname(destination),{recursive:true});await fs.writeFile(destination,html);}
await fs.writeFile(path.join(out,'404.html'),layout('<div class="empty-state"><span class="eyebrow">页面未找到</span><h1>这一页，还没写下来。</h1><p>链接可能已变更，回到文章列表找找看吧。</p><a class="text-link" href="/">回到首页 →</a></div>',{title:'找不到页面',nav:''}));
try{await fs.cp(path.join(root,'content/assets'),path.join(out,'assets'),{recursive:true});}catch(error){if(error.code!=='ENOENT')throw error;}
await fs.writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...pages.keys()].map(url=>`<url><loc>${e(config.origin+encodeURI(url))}</loc></url>`).join('')}</urlset>`);
await fs.writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${config.origin}/sitemap.xml\n`);
console.log(JSON.stringify({pages:pages.size,articles:posts.length,categories:categories.length,missingImages:posts.reduce((total,p)=>total+(p.missingImages||0),0),output:out}));
